name: ci

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.15', '1.14' ]
    name: Build
    steps:
      - name: Setup Go version ${{ matrix.go }}
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}
      - uses: actions/checkout@v2
      - run: |
          mkdir -p /home/runner/go/src/github.com/LoginRadius/
          ln -s /home/runner/work/go-sdk/go-sdk /home/runner/go/src/github.com/LoginRadius/go-sdk
          (cd /home/runner/go/src/github.com/LoginRadius/go-sdk; find)
          go get -t -v -d ./...
          go test -v .
          go build -v .
